language: java
script: gradle dist

install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

env:
  global:
  - LD_LIBRARY_PATH=/home/travis/build/ndw/xmlcalabash1-print/lib/AH
  - secure: fRzeI+ubVUMZ3NX0hWDYbaiERWkcqoZBtIUhXPVdCqGsH9FZXsj3ePGRKH81lbttWsLk6Gly/Psq31BRJUcaOy3e7cp/oxvtxdFt3F/mJWjhvLxWbz5+35S8QqtmCnj0f/OuQDMubmngImNZrme1IK3LGcrgJThiLBrQN+OFx08=
  - secure: Ye/YytX+GglRRL/NPnlXcq+WsUm7tGz737e+4cztBYyzjwBzUd9jb8xIyeZjNYOYd4NYDgM207Egj6AhapIjZWwY4HUXZ3c861iAo7D5OnwLfy5Oi50nJbQUWlz1JpdT0owWWyvMEQk33oF5QVqUzvr2iQapLt27hj7yQj7nWjo=
  - secure: BG6t+dBtbeiMQcYFIXZYffOzAsIpZjbUKKbiaxk+CEd/6dGiflRYCEwrMnf++mjPVF783BifJBkOScCxaJSdE32crvz5tIKaLYnWB2Ov1QYHUOu4cW5yZa3+xfoPT+z5vvZki0bd95phd4azt6ZTPMMMW39jWlPYCqANXG95cHw=

before_install:
- lib/update-lib.sh

after_script:
- rm -rf lib

deploy:
  provider: releases
  api_key:
    secure: P8aApW12eMPtLZyI84izR27jw3083HLsI79taWUmMiEXNQuyvryx8PEc5jNDN3nhHIAw/fadbbwL+Dfqjv6ahgxOUJLsn9hQrsITg+BzZ0LjB2I4Z8W4ufH/LxQlWPPzWaGypVmBwfYUnh1yHVkFA14cBy9gQHOrbqm6b3erHXQ=
  file:
  - build/distributions/xmlcalabash1-print-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
